var namespacenitron =
[
    [ "DataStructureTag", "d2/d09/structnitron_1_1DataStructureTag.html", null ],
    [ "GraphDS", "da/dea/structnitron_1_1GraphDS.html", null ],
    [ "HeterogeneousDS", "d0/df3/structnitron_1_1HeterogeneousDS.html", null ],
    [ "HomogeneousDSTag", "d7/d9a/structnitron_1_1HomogeneousDSTag.html", null ],
    [ "IterableTag", "df/d08/structnitron_1_1IterableTag.html", null ],
    [ "IteratorTag", "d5/dc1/structnitron_1_1IteratorTag.html", null ],
    [ "IValue", "d3/d57/classnitron_1_1IValue.html", "d3/d57/classnitron_1_1IValue" ],
    [ "LinearDSTag", "d0/d08/structnitron_1_1LinearDSTag.html", null ],
    [ "PolymorphicDS", "d5/d3b/structnitron_1_1PolymorphicDS.html", null ],
    [ "Record", "dd/dfe/classnitron_1_1Record.html", "dd/dfe/classnitron_1_1Record" ],
    [ "Singleton", "d4/d0f/classnitron_1_1Singleton.html", "d4/d0f/classnitron_1_1Singleton" ],
    [ "Spec", "de/da5/classnitron_1_1Spec.html", "de/da5/classnitron_1_1Spec" ],
    [ "StaticArray", "da/d78/classnitron_1_1StaticArray.html", "da/d78/classnitron_1_1StaticArray" ],
    [ "Table", "d5/d58/classnitron_1_1Table.html", "d5/d58/classnitron_1_1Table" ],
    [ "Tag", "df/d08/structnitron_1_1Tag.html", "df/d08/structnitron_1_1Tag" ],
    [ "Test", "d9/d08/classnitron_1_1Test.html", "d9/d08/classnitron_1_1Test" ],
    [ "TreeDS", "d6/d0c/structnitron_1_1TreeDS.html", null ],
    [ "TupleDS", "d2/d0b/structnitron_1_1TupleDS.html", null ],
    [ "Value", "d5/d29/classnitron_1_1Value.html", "d5/d29/classnitron_1_1Value" ],
    [ "DataStructureClass", "d1/d5b/conceptnitron_1_1DataStructureClass.html", null ],
    [ "IteratorClass", "d7/dbc/conceptnitron_1_1IteratorClass.html", null ],
    [ "HomogeneousDSClass", "d2/dd1/conceptnitron_1_1HomogeneousDSClass.html", null ],
    [ "IterableClass", "d1/db4/conceptnitron_1_1IterableClass.html", null ],
    [ "LinearDSClass", "dc/d68/conceptnitron_1_1LinearDSClass.html", null ],
    [ "DifferentTypes", "df/d33/conceptnitron_1_1DifferentTypes.html", null ],
    [ "ProperSingleton", "da/d8d/conceptnitron_1_1ProperSingleton.html", null ],
    [ "Streamable", "d8/d47/conceptnitron_1_1Streamable.html", null ],
    [ "TagClass", "d8/d3b/conceptnitron_1_1TagClass.html", null ],
    [ "ForEachFunction", "de/d94/namespacenitron.html#a68d22823d673ba8428e3e0af5e681f7c", null ],
    [ "ReduceFunction", "de/d94/namespacenitron.html#a14e8984438539e84b753313b0a89da35", null ],
    [ "TransformFunction", "de/d94/namespacenitron.html#ac2234e32f1f59d82bb6d5cef0991c5d3", null ],
    [ "ValuePtr", "de/d94/namespacenitron.html#aa4b68cc4ec0c8f5ec8e65792a394d1af", null ]
];